import React from 'react'
import CIcon from '@coreui/icons-react'
import {
  cilBell,
  cilCalculator,
  cilChartPie,
  cilCursor,
  cilDescription,
  cilDrop,
  cilNotes,
  cilPencil,
  cilPuzzle,
  cilSpeedometer,
  cilStar,
} from '@coreui/icons'
import {
  Users,
  ShoppingBag,
  FilePlus,
  List,
  Package,
  Slack,
  ShoppingCart,
  Trello,
} from 'react-feather'
import { CNavGroup, CNavItem, CNavTitle } from '@coreui/react'

const _nav = [
  {
    component: CNavItem,
    name: 'Dashboard',
    permission: 'dashboard',
    to: '/dashboard',
    icon: <Slack style={{ marginRight: '23px' }} />,
  },
  {
    component: CNavItem,
    permission: 'order',
    name: 'Order',
    to: '/orderlist',
    icon: <Package style={{ marginRight: '23px' }} />,
  },
  {
    component: CNavItem,
    permission: 'hunting',
    name: 'HuntingForm',
    to: '/huntingForm',
    icon: <FilePlus style={{ marginRight: '23px' }} />,
  },
  {
    component: CNavItem,
    permission: 'hunting_list',
    name: 'Huntings',
    to: '/huntings',
    icon: <List style={{ marginRight: '23px' }} />,
  },
  {
    component: CNavItem,
    permission: 'view_user',
    name: 'Users',
    to: '/users',
    icon: <Users style={{ marginRight: '23px' }} />,
  },
  {
    component: CNavItem,
    permission: 'view_store',
    name: 'Vendor',
    to: '/vendor',
    icon: <ShoppingBag style={{ marginRight: '23px' }} />,
  },
  {
    component: CNavItem,
    permission: 'view_marketplace',
    name: 'MarketPlace',
    to: '/marketplace',
    icon: <ShoppingCart style={{ marginRight: '23px' }} />,
  },
  {
    component: CNavItem,
    permission: 'view_category',
    name: 'Category',
    to: '/category',
    icon: <Trello style={{ marginRight: '23px' }} />,
  },
  {
    component: CNavTitle,
    permission: 'dashboard',
    name: 'Theme',
  },
  {
    component: CNavItem,
    name: 'Colors',
    permission: 'dashboard',
    to: '/theme/colors',
    icon: <CIcon icon={cilDrop} customClassName="nav-icon" />,
  },
  {
    component: CNavItem,
    name: 'Typography',
    permission: 'dashboard',
    to: '/theme/typography',
    icon: <CIcon icon={cilPencil} customClassName="nav-icon" />,
  },
  {
    component: CNavTitle,
    permission: 'dashboard',
    name: 'Components',
  },
  {
    component: CNavGroup,
    name: 'Base',

    permission: 'dashboard',
    to: '/base',
    icon: <CIcon icon={cilPuzzle} customClassName="nav-icon" />,
    items: [
      {
        component: CNavItem,
        name: 'Accordion',
        to: '/base/accordion',
      },
      {
        component: CNavItem,
        name: 'Breadcrumb',
        permission: 'dashboard',
        to: '/base/breadcrumbs',
      },
      {
        component: CNavItem,
        name: 'Cards',
        permission: 'dashboard',
        to: '/base/cards',
      },
      {
        component: CNavItem,
        name: 'Carousel',
        permission: 'dashboard',
        to: '/base/carousels',
      },
      {
        component: CNavItem,
        name: 'Collapse',
        permission: 'dashboard',
        to: '/base/collapses',
      },
      {
        component: CNavItem,
        name: 'List group',
        permission: 'dashboard',
        to: '/base/list-groups',
      },
      {
        component: CNavItem,
        name: 'Navs & Tabs',
        permission: 'dashboard',
        to: '/base/navs',
      },
      {
        component: CNavItem,
        name: 'Pagination',
        permission: 'dashboard',
        to: '/base/paginations',
      },
      {
        component: CNavItem,
        name: 'Placeholders',
        permission: 'dashboard',
        to: '/base/placeholders',
      },
      {
        component: CNavItem,
        name: 'Popovers',
        permission: 'dashboard',
        to: '/base/popovers',
      },
      {
        component: CNavItem,
        name: 'Progress',
        permission: 'dashboard',
        to: '/base/progress',
      },
      {
        component: CNavItem,
        name: 'Spinners',
        permission: 'dashboard',
        to: '/base/spinners',
      },
      {
        component: CNavItem,
        name: 'Tables',
        permission: 'dashboard',
        to: '/base/tables',
      },
      {
        component: CNavItem,
        name: 'Tooltips',
        permission: 'dashboard',
        to: '/base/tooltips',
      },
    ],
  },
  {
    component: CNavGroup,
    name: 'Buttons',
    to: '/buttons',
    permission: 'dashboard',
    icon: <CIcon icon={cilCursor} customClassName="nav-icon" />,
    items: [
      {
        component: CNavItem,
        name: 'Buttons',
        permission: 'dashboard',
        to: '/buttons/buttons',
      },
      {
        component: CNavItem,
        name: 'Buttons groups',
        permission: 'dashboard',
        to: '/buttons/button-groups',
      },
      {
        component: CNavItem,
        name: 'Dropdowns',
        permission: 'dashboard',
        to: '/buttons/dropdowns',
      },
    ],
  },
  {
    component: CNavGroup,
    name: 'Forms',
    permission: 'dashboard',
    icon: <CIcon icon={cilNotes} customClassName="nav-icon" />,
    items: [
      {
        component: CNavItem,
        name: 'Form Control',
        permission: 'dashboard',
        to: '/forms/form-control',
      },
      {
        component: CNavItem,
        name: 'Select',
        permission: 'dashboard',
        to: '/forms/select',
      },
      {
        component: CNavItem,
        name: 'Checks & Radios',
        permission: 'dashboard',
        to: '/forms/checks-radios',
      },
      {
        component: CNavItem,
        name: 'Range',
        permission: 'dashboard',
        to: '/forms/range',
      },
      {
        component: CNavItem,
        name: 'Input Group',
        permission: 'dashboard',
        to: '/forms/input-group',
      },
      {
        component: CNavItem,
        name: 'Floating Labels',
        permission: 'dashboard',
        to: '/forms/floating-labels',
      },
      {
        component: CNavItem,
        name: 'Layout',
        permission: 'dashboard',
        to: '/forms/layout',
      },
      {
        component: CNavItem,
        name: 'Validation',
        permission: 'dashboard',
        to: '/forms/validation',
      },
    ],
  },
  {
    component: CNavItem,
    name: 'Charts',
    to: '/charts',
    permission: 'dashboard',
    icon: <CIcon icon={cilChartPie} customClassName="nav-icon" />,
  },
  {
    component: CNavGroup,
    name: 'Icons',
    permission: 'dashboard',
    icon: <CIcon icon={cilStar} customClassName="nav-icon" />,
    items: [
      {
        component: CNavItem,
        name: 'CoreUI Free',
        permission: 'dashboard',
        to: '/icons/coreui-icons',
        badge: {
          color: 'success',
          text: 'NEW',
        },
      },
      {
        component: CNavItem,
        name: 'CoreUI Flags',
        to: '/icons/flags',
        permission: 'dashboard',
      },
      {
        component: CNavItem,
        name: 'CoreUI Brands',
        permission: 'dashboard',
        to: '/icons/brands',
      },
    ],
  },
  {
    component: CNavGroup,
    name: 'Notifications',
    permission: 'dashboard',
    icon: <CIcon icon={cilBell} customClassName="nav-icon" />,
    items: [
      {
        component: CNavItem,
        name: 'Alerts',
        permission: 'dashboard',
        to: '/notifications/alerts',
      },
      {
        component: CNavItem,
        name: 'Badges',
        permission: 'dashboard',
        to: '/notifications/badges',
      },
      {
        component: CNavItem,
        name: 'Modal',
        permission: 'dashboard',
        to: '/notifications/modals',
      },
      {
        component: CNavItem,
        name: 'Toasts',
        permission: 'dashboard',
        to: '/notifications/toasts',
      },
    ],
  },
  {
    component: CNavItem,
    name: 'Widgets',
    permission: 'dashboard',
    to: '/widgets',
    icon: <CIcon icon={cilCalculator} customClassName="nav-icon" />,
    badge: {
      color: 'info',
      text: 'NEW',
    },
  },
  {
    component: CNavTitle,
    name: 'Extras',
    permission: 'dashboard',
  },
  {
    component: CNavGroup,
    name: 'Pages',
    permission: 'dashboard',
    icon: <CIcon icon={cilStar} customClassName="nav-icon" />,
    items: [
      {
        component: CNavItem,
        name: 'Login',
        permission: 'dashboard',
        to: '/login',
      },
      {
        component: CNavItem,
        name: 'Register',
        permission: 'dashboard',
        to: '/register',
      },
      {
        component: CNavItem,
        name: 'Error 404',
        to: '/404',
        permission: 'dashboard',
      },
      {
        component: CNavItem,
        name: 'Error 500',
        to: '/500',
        permission: 'dashboard',
      },
    ],
  },
  {
    component: CNavItem,
    name: 'Docs',
    permission: 'dashboard',
    href: 'https://coreui.io/react/docs/templates/installation/',
    icon: <CIcon icon={cilDescription} customClassName="nav-icon" />,
  },
]

export default _nav
